### ISSUE TITLE
Re-enable golangci-lint

### ISSUE THREAD

**Issue by benmoss** [buildkite/agent-stack-k8s#108]
In #107 I'm disabling it since I'm hitting weird issues like https://buildkite.com/buildkite-kubernetes-stack/kubernetes-agent-stack/builds/294#_

```
ERRO Running error: context loading failed: no go files to analyze
```
 
I have no idea why that's happening but can't be bothered to troubleshoot that right now. Linter is not providing a ton of value and is pretty slow because of the lack of caching.

**Comment by triarius** [comment]
Seems to be working more consistently after I refactored to use the golangci-lint container.
