### ISSUE TITLE
Cleanup jobs that are canceled

### ISSUE THREAD

**Issue by benmoss** [buildkite/agent-stack-k8s#133]
We sometimes seem jobs that get stuck for some reason (misconfiguration, etc) that causes them to get into a unrecoverable state. If a user hits "cancel" on the Buildkite UI, we should notice this and delete the job from Kubernetes.

Most of the time the agent will see the cancellation and do cleanup, but there are still times when the agent has failed or hasn't started that the job can be orphaned.

We could do this with a background task that periodically fetches builds we are tracking and checks their status on the Buildkite API.

**Comment by DrJosh9000** [comment]
Fixed by #406 and #442.
