### ISSUE TITLE
Allow customized labels for helm chart deployment in spinnaker

### ISSUE THREAD

**Issue by jiaquan1** [buildkite/agent-stack-k8s#170]
I am trying to deploy this helm chart in my org spinnaker, it requires org-specific labels, but the helm chart yaml config did not allow user-input labels. It's better to allow user-input labels into helm chart config yaml.

**Comment by 80degreeswest** [comment]
Also would need to allow limits for cpu/ram as our eks cluster requires those as well. This should provide for a greater flexibility with different eks cluster setups. It's currently a blocker for us to deploy this solution.

**Comment by triarius** [comment]
> Also would need to allow limits for cpu/ram as our eks cluster requires those as well. This should provide for a greater flexibility with different eks cluster setups. It's currently a blocker for us to deploy this solution.

@80degreeswest I believe that's already possible. Just specify `requests` and `limits` in the values, like what's done here:
https://github.com/buildkite/agent-stack-k8s/blob/6f1cc7a38c9d859bef94ccc3422b9e6c348a22dc/charts/agent-stack-k8s/values.yaml#L9-L12

If that's not what you're looking for, can you make a new issue with more details?

**Comment by 80degreeswest** [comment]
@triarius you are right I originally missed it there.

**Comment by triarius** [comment]
This has now been released in v0.6.0
