### ISSUE TITLE
agentStackSecret still requires agentToken and graphqlToken

### ISSUE THREAD

**Issue by chulkilee** [buildkite/agent-stack-k8s#181]
Seems like helm values schema check doesn't let me use agentStackSecret instead of agentToken and graphqlToken.

```
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
agent-stack-k8s:
- agentToken: String length must be greater than or equal to 1
- graphqlToken: String length must be greater than or equal to 1
```

Workaround: pass any value to pass the values schema validation.

**Comment by chulkilee** [comment]
I found that the latest helm chart (0.5.1) does not have this feature 🤦  - so created #183

**Comment by triarius** [comment]
Yeah, we have made [v0.6.0](https://github.com/buildkite/agent-stack-k8s/releases/tag/v0.6.0) now.
