### ISSUE TITLE
Publish new chart

### ISSUE THREAD

**Issue by chulkilee** [buildkite/agent-stack-k8s#183]
0.5.1 does not support overriding token - please release the new version!

**Comment by triarius** [comment]
Hi @chulkilee [v0.6.0](https://github.com/buildkite/agent-stack-k8s/releases/tag/v0.6.0) should have this incorporated.

**Comment by chulkilee** [comment]
@triarius Do we have new chart released? Seems like 0.6.0 chart is still using 0.5.1

```
$ helm show chart oci://ghcr.io/buildkite/helm/agent-stack-k8s

Pulled: ghcr.io/buildkite/helm/agent-stack-k8s:0.6.0
Digest: sha256:3efafde9c027a8c43bb727020b733c199bf4ee6809f53f2240598309f61b7bbe
apiVersion: v2
appVersion: 0.5.1-83-g2661fad
description: A Helm chart for the Buildkite Kubernetes agent stack
name: agent-stack-k8s
type: application
version: 0.5.1-83-g2661fad
```

**Comment by triarius** [comment]
Hmm, the commit: 2661fad has the tag v0.6.0, so the code should be the same. We reuse previously built container images in the release process, so this is most likely what's causing it.

Does the feature you need from v0.6.0 work despite this?

**Comment by chulkilee** [comment]
Wait, now it creates 0.6.0 images correctly. It still doesn't pick up my custom secret but that's a separate issue so I'll create new one. Thanks!
