### ISSUE TITLE
controller uses custom secret but job is using the default secret not the custom one

### ISSUE THREAD

**Issue by chulkilee** [buildkite/agent-stack-k8s#186]
controller (from deployment) uses the custom secret passed via helm - but created job does not pick it up. 

I believe this is because configmap is not storing the custom info at https://github.com/buildkite/agent-stack-k8s/blob/v0.6.0/charts/agent-stack-k8s/templates/config.yaml.tpl

**Comment by triarius** [comment]
Thanks for reporting this @chulkilee! I've made a PR, and we will release it shortly.
