### ISSUE TITLE
Support multiple queue tags

### ISSUE THREAD

**Issue by scalapaymdacrema** [buildkite/agent-stack-k8s#241]
When launching the controller with multiple queue tags it doesn't pick up any job from the pipeline resulting in pipelines in stuck waiting for agent.

Version 0.7.0 
Startup log: ( org value is masked ) 
`2024-01-18T08:26:10.909Z	INFO	controller/controller.go:122	configuration loaded	{"config": {"agent-token-secret": "dev-eks-buildkite-agent-stack-secrets", "debug": true, "image": "ghcr.io/buildkite/agent-stack-k8s/agent:0.7.0", "job-ttl": "1h0m0s", "max-in-flight": 0, "namespace": "buildkite", "org": "mytestorg", "profiler-address": "", "cluster-uuid": "", "tags": ["queue=dev-eks", "queue=dev-cat-eks"]}}
2024-01-18T08:26:11.011Z	INFO	monitor	monitor/monitor.go:113	started	{"org": "mytestorg"}`

**Comment by triarius** [comment]
Hi @scalapaymdacrema thanks for raising this.

I think the intention with queues is that 1 queue corresponds to 1 stack. If you want to run jobs on Kubernetes for multiple queues, we recommend you run multiple Charts in separate namespaces.

We'll update the docs to make this more clear.

**Comment by scalapaymdacrema** [comment]
Hi @triarius I'm writing to update this issue since I found in the documentation that multiple tags are supported for listening on multiple queues so I believe it should behave the same way
ref. https://buildkite.com/docs/agent/v3/queues
