### ISSUE TITLE
Specifying kubernetes plugin version does not work

### ISSUE THREAD

**Issue by artem-zinnatullin** [buildkite/agent-stack-k8s#388]
Currently the [documentation suggests](https://github.com/buildkite/agent-stack-k8s/blob/9077705b68031612fa1d26d6b1a9b409990f4c35/README.md#L196) using the plugin via its internal name **_without a version_** which is a recipe for disaster when an incompatible release is inevitably out:

```js
plugins:
  - kubernetes:
       podSpec:
       …
```

When I attempt to specify version as per [Buildkite using plugins docs](https://buildkite.com/docs/plugins/using#adding-a-plugin-to-your-pipeline) like so:

```js
plugins:
  - kubernetes#v0.15.0:
       podSpec:
       …
```

The build fails trying to find the plugin:

```js
Preparing plugins | 3s
-- | --
  | # Plugin "github.com/buildkite-plugins/kubernetes-buildkite-plugin" will be checked out to "/workspace/plugins/buildkite/github-com-buildkite-plugins-kubernetes-buildkite-plugin-v0-15-0"
  | # Switching to the temporary plugin directory
  | $ cd /workspace/plugins/github-com-buildkite-plugins-kubernetes-buildkite-plugin-v0-15-0953355686
  | $ git clone -v --recursive -- https://github.com/buildkite-plugins/kubernetes-buildkite-plugin .
  | Cloning into '.'...
  | fatal: could not read Username for 'https://github.com': terminal prompts disabled
  | $ git clone -v --recursive -- https://github.com/buildkite-plugins/kubernetes-buildkite-plugin .
  | Cloning into '.'...
  | fatal: could not read Username for 'https://github.com': terminal prompts disabled
  | $ git clone -v --recursive -- https://github.com/buildkite-plugins/kubernetes-buildkite-plugin .
  | Cloning into '.'...
  | fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

---

If I try specifying full git repo with version:

```js
plugins:
  - https://github.com/buildkite/agent-stack-k8s.git#v0.15.0:
       podSpec:
       …
```

Then plugin is resolved, but doesn't work fully, it doesn't apply `podSpec` and `podSpecPatch` correctly 🤷 .

---

**Question:** What is the proper way to specify version of the plugin in the Buildkite pipeline to have it fixed and avoid unexpected upgrades? Thanks!

**Comment by DrJosh9000** [comment]
Thanks for the question @artem-zinnatullin!

`kubernetes` is not a real plugin - it's parsed by the agent-stack-k8s controller and removed from the job before it is passed to buildkite-agent within the pod it runs.

If you put a version on the end, it escapes that logic. Because there is no "real" plugin (which would be at `github.com/buildkite-plugins/kubernetes-buildkite-plugin` if it existed) it can't be pulled and fails.

The `kubernetes` block exists within plugins as a workaround to allow iterating on the configurable features without having to change how Buildkite parses pipelines. As it stabilises, we should figure out how to move it out of `plugins` so that this question becomes moot.

**Comment by artem-zinnatullin** [comment]
Ohhhhhhhhhh, I see.

So essentially the "version" of kubernetes "plugin" is 100% dependent on version of `agent-stack-k8s` controller you have deployed because it reads the configuration! That actually makes total sense, I'll give docs another reading pass and will submit a PR to clarify that if needed.

Thank you for answering, @DrJosh9000!

**Comment by CtfChan** [comment]
This [section](https://github.com/buildkite/agent-stack-k8s) still saids to use "kubernetes" should this be changed?

```
steps:
- label: Hello World!
  agents:
    queue: kubernetes
  plugins:
  - kubernetes:
      podSpec:
        containers:
        - image: alpine:latest
          command:
          - echo Hello World!
```
