### ISSUE TITLE
controller jobs failing with `cp: can't stat '/sbin/tini-static': No such file or directory`

### ISSUE THREAD

**Issue by wallyqs** [buildkite/agent-stack-k8s#410]
I have been using :latest from the image `ghcr.io/buildkite/agent-stack-k8s/controller:latest` and recently the jobs started failing with the following and not getting results:

```
kubectl -n buildkite logs buildkite-0192e235-5ef8-4375-951e-287b17b1da50-zl444 -c copy-agent

cp: can't stat '/sbin/tini-static': No such file or directory
```

**Comment by wallyqs** [comment]
Reverting to [v0.16.1](https://github.com/buildkite/agent-stack-k8s/releases/tag/v0.16.1) based image seems to have fixed the issue.

**Comment by DrJosh9000** [comment]
`tini-static` was added to [the agent image](https://github.com/buildkite/agent/pkgs/container/agent/296725358?tag=3.84.0) in the last release, and that should be the default image used by the controller. Have you configured a different agent image?

**Comment by DrJosh9000** [comment]
I'm closing this off since I haven't heard back from you, but if this is still happening with a newer agent image or with `/sbin/tini-static` installed in a custom image, please comment or open a new issue.
