### ISSUE TITLE
Optimization possible to avoid pulling each container image twice

### ISSUE THREAD

**Issue by dziemba** [buildkite/agent-stack-k8s#411]
I think there’s an optimization that can be done in the agent-stack-k8s regarding image pulling. I understand the reasoning for the init-containers/preFlightContainers (see https://github.com/buildkite/agent-stack-k8s/blob/00a778db02818843253416d6833ff0199d8ea13c/internal/controller/scheduler/scheduler.go#L510) and I think that’s a reasonable solution. 

Then however we do another pull for each image here: https://github.com/buildkite/agent-stack-k8s/blob/00a778db02818843253416d6833ff0199d8ea13c/internal/controller/scheduler/scheduler.go#L357 which I believe is not necessary since we just pulled all these images via the init-containers. 

In our clusters a no-op pull takes roughly a second, so this adds a second for each container used. When using many containers (we often have 5+), this adds up to quite a lot of extra time waiting. I believe it’s possible to just change the PullPolicy to Never to avoid this extra pulling, which is fine since we just pre-pulled the images in the init containers.

**Comment by DrJosh9000** [comment]
Thanks for raising this @dziemba! This proposal seems sensible to me.

**Comment by DrJosh9000** [comment]
I wonder if its worth choosing `PullIfNotPresent` over `PullNever`, on the (admittedly very very unlikely) chance that the image disappears in between the init container pulling and the regular containers starting?

**Comment by dziemba** [comment]
Thanks for the quick fix! Yes, `PullIfNotPresent` is probably the better choice.
