### ISSUE TITLE
NodeSelector parse error in configfile

### ISSUE THREAD

**Issue by tssala23** [buildkite/agent-stack-k8s#452]
I am  trying to add a node selector into the into the generated [config.yaml](https://github.com/buildkite/agent-stack-k8s/blob/4de522d1b77e5ca04a079bd213a13801eba364dc/charts/agent-stack-k8s/templates/config.yaml.tpl) file. This is because I want the pods that run the steps to land on a specific node. Adding a node selector to the deployment lands the agent on that node but does not ensure that the pods that run the steps also land on that node.
Adding it into the pod spec patch in the configmap like this:
```
pod-spec-patch:
      nodeSelector:
        kubernetes.io/hostname: "wrk-4"
      containers:
      - name: agent
      - name: checkout
      - name: container-0
        image: image-registry.openshift-image-registry.svc:5000/buildkite/vllm-main-test:latest
      initContainers:
      - name: copy-agent
```
Yields this error:
```
Error: failed to parse config: failed to parse config: 1 error(s) decoding:

* 'pod-spec-patch.nodeSelector[kubernetes]' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[io/hostname:wrk-4]'
2024/12/11 20:29:02 failed to parse config: failed to parse config: 1 error(s) decoding:

* 'pod-spec-patch.nodeSelector[kubernetes]' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[io/hostname:wrk-4]'
```
I get the same error wrapping the label in quote i.e, `"kubernetes.io/hostname"`

**Comment by DrJosh9000** [comment]
Hi @tssala23, thanks for raising the issue. 

Can you confirm which version of the stack this is running on? This looks like the bug fixed by #409, released in v0.18.0.

**Comment by tssala23** [comment]
@DrJosh9000 Thank you for the response.
I installed using helm template a couple months back so I think you may be right.
Would the quickest solution be to just change to controller image in [the deployment](https://github.com/tssala23/buildkite/blob/7511f4e0213b23281b4d52872eb5585e3a79f845/apps/deployments/agent-stack-k8s/deployment.yaml#L25)?

**Comment by tssala23** [comment]
@DrJosh9000 Brilliant, that worked, thank you very much for the help
